title: Sumanth Habib
description: Data Scientist @ Tiger Analytics!!
show_downloads: true
theme: jekyll-theme-hacker
header_pages:
  - about.md
navigation:
  - Home: /
  - About: /about
  - Contact: /contact
